xen-image-minimal: Add missing dependency causing intermittent failures
Source: meta-virtualization
MR: 158407
Type: Integration
Disposition: Merged from meta-virtualization
ChangeID: 54b806b1985f3989722ee308e1073530fe3328c1
Description:

"bitbake xen-image-minimal -c do_image_wic" fails with:

| ERROR: _exec_cmd: install -m 0644 tmp/deploy/images/qemux86-64/xen-qemux86-64.gz tmp/work/qemux86_64-poky-linux/xen-image-minimal/1.0/tmp-wic/hdd/boot/xen.gz returned '1' instead of 0
| output: install: cannot stat 'tmp/deploy/images/qemux86-64/xen-qemux86-64.gz': No such file or directory
|
| WARNING: exit code 1 from a shell command.
ERROR: Task (/media/build/poky/meta-virtualization/recipes-extended/images/xen-image-minimal.bb:do_image_wic) failed with exit code '1'

Add the missing dependency to avoid this.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>