podman: require catatonit
Source: meta-virtualization
MR: 296372
Type: Integration
Disposition: Merged from meta-virtualization
ChangeID: 3f6c931b8a6ad63d0a0da746895059f64d50a505
Description:

Alternatively, we could add it to RRECOMMENDS. But I would say, given
its name, managing pods is part of podman's core functionality and that
requires catatonit, which is currently only pulled in for the ptest:

root@qemux86-64:~# podman pod create
Error: building local pause image: finding pause binary: exec: "catatonit": executable file not found in $PATH

Signed-off-by: Patrick Wicki <patrick.wicki@siemens.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
(cherry picked from commit 380eae7bdd14319069960f7eb8d82c0ec0608b8a)

Signed-off-by: Oliver Kästner <okaestner@rosen-nxt.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>