libvirt: fix parallel build race in generated protocol headers
Source: https://gitlab.com/libvirt/libvirt
MR: 730019
Type: Defect Fix
Disposition: Needs submitting to meta-virtualization
ChangeID: d3f0312a9439d3c7dba7cc93a0f0814f000f0d76
Description:

The Meson dependency graph does not make daemon compilation depend on
the generated remote protocol headers. In parallel builds, Ninja may
therefore compile remote_daemon_dispatch.c before lxc_protocol.h exists:

    ../libvirt-10.0.0/src/remote/remote_daemon.h:28:10: fatal error:
    lxc_protocol.h: No such file or directory

Backport the upstream fix, which makes each daemon depend on the
generated protocol sources and headers.

Upstream commit: dcfe548cb01d64e2bdeac456c428e578158232b9

Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>