lxc: fix compile failure on gcc10
Source: meta-virtualization
MR: 110392
Type: Integration
Disposition: Merged from meta-virtualization
ChangeID: 41e4f18f96538af0f13409597541295a9c26aeca
Description:

Since oe-core is upgrading gcc to 10.1, there is
a compile failure
...
|../../../lxc-4.0.2/src/lxc/cgroups/cgfsng.c:2100:10: error: writing
1 byte into a region of size 0 [-Werror=stringop-overflow=]
| 2100 |   *slash = '\0';
...

Add gcc option `-Werror=stringop-overflow' to workaround the issue

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>