cockpit-machines: remove autotools inheritance
The commit [1] from openembedded-core, removes the possibility to use
autotools bbclass when the configure script is missing. Because the
cockpit-machines release tarball always ships pre-built assets in dist/,
there is no need to use autotools to build the package.

This commit fixes the following build error:
    ERROR: cockpit-machines-346-r0 do_configure: no configure script
    found at ./configure

[1]: autotools: require that a configure script exists
    SHA: 6d327a39befae44a88a812bdf4acde800dcee57b

Signed-off-by: Tanguy Raufflet <tanguy.raufflet@savoirfairelinux.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>