libvirt: set USERADD_DEPENDS to avoid package_write_rpm failure
Source: meta-virtualization
MR: 166943
Type: Integration
Disposition: Merged from meta-virtualization
ChangeID: 7c78f4ef96020b702c027d179895c9f97179b4fc
Description:

When do_package uses state cache and is not re-run but do_package_write_rpm
is re-run, then we get the following error:

  Exception: KeyError: 'getpwuid(): uid not found: 996'

This is because libvirt does chown to polkitd in do_install and polkitd
is from polkit.

Here's an easy way to reproduce this issue:

  bitbake libvirt -c cleansstate && bitbake libvirt -c package && \
  bitbake libvirt -c clean && bitbake libvirt -c package_write_rpm

So make use of USERADD_DEPENDS to ensure polkitd exists to fix this issue.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>